# Generated by Django 4.2 on 2025-01-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_nickname_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chatbot_image',
            field=models.ImageField(blank=True, null=True, upload_to='chatbots/'),
        ),
    ]
