# Generated by Django 4.2 on 2025-01-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='response',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='messages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
