# Generated by Django 4.2 on 2025-01-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_group',
            field=models.CharField(choices=[('10S', '10대'), ('20S', '20대'), ('30S', '30대'), ('40S', '40대'), ('50S', '50대'), ('60P', '60대 이상')], default='30', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
